package analisador.parsers;

import static analisador.constants.SemanticActionsConstant.*;

import analisador.constants.LMSConstantTokens;

public class LMSParserTable extends LMSConstantTokens {
	
	public static LMSParserTable instance;
	public static final int NI = -1;
	
    public final int START_SYMBOL = 46;
    public final int FIRST_NON_TERMINAL = 46;
    public final int FIRST_SEMANTIC_ACTION = 77;
    
    public static LMSParserTable getInstance() {
    	return (instance == null) ? new LMSParserTable() : instance;
    }

    public final int[][] LMS_PARSER_TABLE = {
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  0, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  1, NI, NI,  1, NI, NI, NI, NI, NI, NI, NI, NI, NI,  1, NI, NI, NI, NI, NI, NI,  1, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  2, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI,  4, NI, NI,  3, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  8, NI, NI,  5, NI, NI, NI, NI, NI, NI, NI, NI, NI,  8, NI, NI, NI, NI, NI, NI,  8, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  7, NI, NI, NI,  6, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI,  6, NI, NI, NI, NI, NI, NI,  6, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 12, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 12, NI, NI, NI, NI, NI, NI,  9, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 11, NI, NI, NI, 10, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 10, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 13, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 15, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 14, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, 16, NI, NI, NI, 17, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 18, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, 20, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 19, 19, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 19, NI, NI, NI },
            { NI, NI, 23, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 21, NI, NI, NI, 22, 24, 43, NI, NI, 23, 23, 49, 29, NI, NI, NI, NI, NI, NI, 34, 33, NI, NI, 23, NI, 32, 38 },
            { NI, NI, 25, NI, NI, NI, 26, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 25, 25, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 25, NI, NI, NI },
            { NI, 28, NI, NI, NI, NI, NI, 27, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, 30, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 31, 30, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 30, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 35, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 37, NI, NI, NI, NI, NI, 36, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, 40, NI, NI, NI, 40, 40, NI, NI, NI, NI, NI, NI, 40, 40, 39, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 40, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 42, NI, NI, NI, NI, NI, 41, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 44, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 45, NI, NI, START_SYMBOL, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, 48, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 47, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, 50, NI, NI, NI, 50, 50, NI, NI, NI, NI, NI, NI, 50, 50, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 50, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 51, 51, NI, NI, NI, NI, 51, NI, NI, NI, NI, 53, 54, 56, 55, 57, 52, NI, NI, NI, NI, NI, NI, NI, NI, 51, 51, 51, NI, NI, NI, NI, 51, NI, NI, NI, NI, NI, 51, 51, 51, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, 60, NI, NI, NI, 59, 58, NI, NI, NI, NI, NI, NI, 60, 60, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 60, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 64, 64, NI, NI, NI, NI, 64, NI, NI, 62, 61, 64, 64, 64, 64, 64, 64, NI, NI, NI, NI, NI, NI, NI, NI, 64, 64, 64, NI, NI, NI, NI, 64, 63, NI, NI, NI, NI, 64, 64, 64, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, 65, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 65, 65, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 65, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI },
            { NI, 66, 66, NI, NI, NI, NI, 66, 67, 68, 66, 66, 66, 66, 66, 66, 66, 66, NI, NI, NI, 69, NI, NI, NI, NI, 66, 66, 66, NI, NI, NI, NI, 66, 66, NI, NI, NI, NI, 66, 66, 66, NI, NI, NI },
            { NI, NI, NI, NI, NI, NI, 71, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 73, 70, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, 72, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI, NI }
        };
    
	public final int[][] LMS_PRODUCTIONS = {
    		{TOKEN_PROGRAM, TOKEN_IDENTIFICADOR, RECONHECE_NOME_PROGRAMA, TOKEN_PONTO_VIRGULA, 47, TOKEN_PONTO, RECONHECE_FINAL_PROGRAMA},
    		{50, 52, APOS_DECLARACAO_VARIAVEL, 55, 57},
    		{TOKEN_IDENTIFICADOR, ENCONTRADO_ROTULO_VAR_PARAMETRO, 49},
    		{TOKEN_EPSILON},
    		{TOKEN_VIRGULA, TOKEN_IDENTIFICADOR, ENCONTRADO_ROTULO_VAR_PARAMETRO, 49},
    		{TOKEN_CONST, TOKEN_IDENTIFICADOR, RECONHECIDO_NOME_CONSTANTE_DECLARACAO, TOKEN_COMPARACAO_IGUAL, TOKEN_NUMERAL, RECONHECIDO_VALOR_CONSTANTE_DECLARACAO, TOKEN_PONTO_VIRGULA, 51},
    		{TOKEN_EPSILON},
    		{TOKEN_IDENTIFICADOR, RECONHECIDO_NOME_CONSTANTE_DECLARACAO, TOKEN_COMPARACAO_IGUAL, TOKEN_NUMERAL, RECONHECIDO_VALOR_CONSTANTE_DECLARACAO, TOKEN_PONTO_VIRGULA, 51},
    		{TOKEN_EPSILON},
    		{TOKEN_VAR, BEFORE_LISTA_IDENTIFICADORES_DECLARACAO_VARIAVEIS, 48, TOKEN_DOIS_PONTOS, 54, TOKEN_PONTO_VIRGULA, 53},
    		{TOKEN_EPSILON},
    		{48, TOKEN_DOIS_PONTOS, 54, TOKEN_PONTO_VIRGULA, 53},
    		{TOKEN_EPSILON},
    		{TOKEN_INTEGER},
    		{TOKEN_PROCEDURE, TOKEN_IDENTIFICADOR, AFTER_NOME_PROCEDURE_DECLARACAO, 56, TOKEN_PONTO_VIRGULA, AFTER_DECLARACAO_PROCEDURE, 47, TOKEN_PONTO_VIRGULA, FIM_PROCEDURE, 55},
    		{TOKEN_EPSILON},
    		{TOKEN_EPSILON},
    		{TOKEN_ABRE_PARENTESES, BEFORE_PARAMETROS_FORMAIS_PROCEDURE, 48, TOKEN_DOIS_PONTOS, TOKEN_INTEGER, TOKEN_FECHA_PARENTESES},
    		{TOKEN_BEGIN, 59, 58, TOKEN_END},
    		{TOKEN_EPSILON},
    		{TOKEN_PONTO_VIRGULA, 59, 58},
    		{TOKEN_IDENTIFICADOR, ATRIBUICAO_PARTE_ESQUERDA, TOKEN_ATRIBUICAO, 70, AFTER_EXPRESSAO_ATRIBUICAO},
    		{57},
    		{TOKEN_EPSILON},
    		{TOKEN_CALL, TOKEN_IDENTIFICADOR, CHAMADA_PROCEDURE, 60, AFTER_CALL},
    		{TOKEN_EPSILON},
    		{TOKEN_ABRE_PARENTESES, 70, AFTER_EXPRESSAO_COMANDO_CALL, 61, TOKEN_FECHA_PARENTESES},
    		{TOKEN_EPSILON},
    		{TOKEN_VIRGULA, 70, AFTER_EXPRESSAO_COMANDO_CALL, 61},
    		{TOKEN_IF, 70, AFTER_EXPRESSAO_NUM_IF, TOKEN_THEN, 59, 62, AFTER_INSTRUCAO_IF},
    		{TOKEN_EPSILON},
    		{AFTER_DOMINIO_THEN_BEFORE_ELSE, TOKEN_ELSE, 59},
    		{TOKEN_WHILE, COMANDO_WHILE_BEFORE_EXPRESSAO, 70, COMANDO_WHILE_AFTER_EXPRESSAO, TOKEN_DO, 59, AFTER_WHILE},
    		{TOKEN_REPEAT, REPEAT_INICIO, 59, TOKEN_UNTIL, 70, REPEAT_FIM},
    		{TOKEN_READLN, READLN_INICIO, TOKEN_ABRE_PARENTESES, 63, 64, TOKEN_FECHA_PARENTESES},
    		{TOKEN_IDENTIFICADOR, IDENTIFICADOR_VARIAVEL},
    		{TOKEN_EPSILON},
    		{TOKEN_VIRGULA, 63, 64},
    		{TOKEN_WRITELN, TOKEN_ABRE_PARENTESES, 65, 66, TOKEN_FECHA_PARENTESES},
    		{TOKEN_LITERAL, AFTER_LITERAL_NA_INSTRUCAO_WRITELN},
    		{70, WRITELN_AFTER_EXPRESSAO},
    		{TOKEN_EPSILON},
    		{TOKEN_VIRGULA, 65, 66},
    		{TOKEN_CASE, AFTER_RESERVADA_CASE, 70, TOKEN_OF, 67, TOKEN_END, AFTER_COMANDO_CASE},
    		{TOKEN_NUMERAL, 68, TOKEN_DOIS_PONTOS, RAMO_CASE_AFTER_INTEIRO_ULTIMO_LISTA, 59, AFTER_COMANDO_EM_CASE, 69},
    		{TOKEN_VIRGULA, RAMO_CASE_AFTER_INTEIRO, TOKEN_NUMERAL, 68},
    		{TOKEN_EPSILON},
    		{TOKEN_EPSILON},
    		{TOKEN_PONTO_VIRGULA, 67},
    		{TOKEN_FOR, TOKEN_IDENTIFICADOR, AFTER_VARIAVEL_CONTROLE_FOR, TOKEN_ATRIBUICAO, 70, AFTER_EXPRESSAO_VALOR_INICIAL, TOKEN_TO, 70, AFTER_EXPRESSAO_VALOR_FINAL, TOKEN_DO, 59, AFTER_COMANDO_EM_FOR},
    		{72, 71},
    		{TOKEN_EPSILON},
    		{TOKEN_COMPARACAO_IGUAL, 72, COMPARACAO_01},
    		{TOKEN_COMPARACAO_MENOR, 72, COMPARACAO_02},
    		{TOKEN_COMPARACAO_MAIOR, 72, COMPARACAO_03},
    		{TOKEN_COMPARACAO_MAIOR_IGUAL, 72, COMPARACAO_04},
    		{TOKEN_COMPARACAO_MENOR_IGUAL, 72, COMPARACAO_05},
    		{TOKEN_COMPARACAO_DIFERENTE, 72, COMPARACAO_06},
    		{TOKEN_OPERACAO_ADICIONA, 74, 73},
    		{TOKEN_OPERACAO_SUBTRAI, 74, EXPRESSAO_OPERANDO_SINAL_UNARIO, 73},
    		{74, 73},
    		{TOKEN_OPERACAO_ADICIONA, 74, EXPRESSAO_SOMA, 73},
    		{TOKEN_OPERACAO_SUBTRAI, 74, EXPRESSAO_SUBTRACAO, 73},
    		{TOKEN_OR, 74, EXPRESSAO_OR, 73},
    		{TOKEN_EPSILON},
    		{76, 75},
    		{TOKEN_EPSILON},
    		{TOKEN_OPERACAO_MULTIPLICA, 76, EXPRESSAO_MULTIPLICA, 75},
    		{TOKEN_OPERACAO_DIVIDE, 76, EXPRESSAO_DIVISAO, 75},
    		{TOKEN_AND, 76,EXPRESSAO_AND, 75},
    		{TOKEN_NUMERAL, EXPRESSAO_INT},
    		{TOKEN_ABRE_PARENTESES, 70, TOKEN_FECHA_PARENTESES},
    		{TOKEN_NOT, 76, EXPRESSAO_NOT},
    		{EXPRESSAO_VARIAVEL, 63}
    		};

    public final int[][] LMS_PRODUCTIONS_OLD = {
        {37, 19, 3, 47, 4},
        {50, 52, 55, 57},
        {19, 49},
        {0},
        {2, 19, 49},
        {26, 19, 18, 20, 3, 51},
        {0},
        {19, 18, 20, 3, 51},
        {0},
        {43, 48, 5, 54, 3, 53},
        {0},
        {48, 5, 54, 3, 53},
        {0},
        {32},
        {36, 19, 56, 3, 47,  3, 55},
        {0},
        {0},
        {7, 48, 5, 32, 8},
        {23, 59, 58, 29},
        {0},
        {3, 59, 58},
        {19, 6, 70},
        {57},
        {0},
        {24, 19, 60},
        {0},
        {7, 70, 61, 8},
        {0},
        {2, 70, 61},
        {31, 70, 40, 59, 62},
        {0},
        {28, 59},
        {44, 70, 27, 59},
        {39, 59, 42, 70},
        {38, 7, 63, 64, 8},
        {19},
        {0},
        {2, 63, 64},
        {45, 7, 65, 66, 8},
        {21},
        {70},
        {0},
        {2, 65, 66},
        {25, 70, 34, 67, 29},
        {20, 68, 5, 59, 69},
        {2, 20, 68},
        {0},
        {0},
        {3, 67},
        {30, 19,  6, 70, 41, 70, 27, 59},
        {72, 71},
        {0},
        {18, 72},
        {13, 72},
        {14, 72},
        {16, 72},
        {15, 72},
        {17, 72},
        {12, 74, 73},
        {11, 74, 73},
        {74, 73},
        {12, 74, 73},
        {11, 74, 73},
        {35, 74, 73},
        {0},
        {76, 75},
        {0},
        {9, 76, 75},
        {10, 76, 75},
        {22, 76, 75},
        {20},
        {7, 70, 8},
        {33, 76},
        {63}
    };

    public final String[] LMS_PARSER_ERROR = {
        "",
        "Era esperado fim de programa",
        "Era esperado \",\"",
        "Era esperado \";\"",
        "Era esperado \".\"",
        "Era esperado \":\"",
        "Era esperado \":=\"",
        "Era esperado \"(\"",
        "Era esperado \")\"",
        "Era esperado \"*\"",
        "Era esperado \"/\"",
        "Era esperado \"-\"",
        "Era esperado \"+\"",
        "Era esperado \"<\"",
        "Era esperado \">\"",
        "Era esperado \"<=\"",
        "Era esperado \">=\"",
        "Era esperado \"<>\"",
        "Era esperado \"=\"",
        "Era esperado identificador",
        "Era esperado numeral",
        "Era esperado literal",
        "Era esperado and",
        "Era esperado begin",
        "Era esperado call",
        "Era esperado case",
        "Era esperado const",
        "Era esperado do",
        "Era esperado else",
        "Era esperado end",
        "Era esperado for",
        "Era esperado if",
        "Era esperado integer",
        "Era esperado not",
        "Era esperado of",
        "Era esperado or",
        "Era esperado procedure",
        "Era esperado program",
        "Era esperado readln",
        "Era esperado repeat",
        "Era esperado then",
        "Era esperado to",
        "Era esperado until",
        "Era esperado var",
        "Era esperado while",
        "Era esperado writeln",
        "<PROGRAMA> inválido",
        "<BLOCO> inválido",
        "<LID> inválido",
        "<REPIDENTIFICADOR> inválido",
        "<DCLCONST> inválido",
        "<LDCONST> inválido",
        "<DCLVAR> inválido",
        "<LDVAR> inválido",
        "<TIPO> inválido",
        "<DCLPROC> inválido",
        "<DEFPAR> inválido",
        "<CORPO> inválido",
        "<REPCOMANDO> inválido",
        "<COMANDO> inválido",
        "<PARAMETROS> inválido",
        "<REPPAR> inválido",
        "<ELSEPARTE> inválido",
        "<VARIAVEL> inválido",
        "<REPVARIAVEL> inválido",
        "<ITEMSAIDA> inválido",
        "<REPITEM> inválido",
        "<CONDCASE> inválido",
        "<RPNUMERAL> inválido",
        "<CONTCASE> inválido",
        "<EXPRESSAO> inválido",
        "<REPEXPSIMP> inválido",
        "<EXPSIMP> inválido",
        "<REPEXP> inválido",
        "<TERMO> inválido",
        "<REPTERMO> inválido",
        "<FATOR> inválido"
    };

}
